### ISSUE TITLE
Important!

### ISSUE THREAD

**Issue by Tooconfident** [amitkb3/prj-rev-bwfs-dasmoto#1]
https://github.com/amitkb3/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtNCraft/index.html#L10
https://github.com/amitkb3/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtNCraft/index.html#L18
https://github.com/amitkb3/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtNCraft/index.html#L26

It's good practice to make sure that if you are using the same CSS selector for multiple sections, that you make is class rather than an id. Id's are usually meant for one html element being styled that will not be shared any where else on the document.

**Comment by amitkb3** [comment]
thanks for your feedback.
