### ISSUE TITLE
Important!

### ISSUE THREAD

**Issue by Tooconfident** [amitkb3/prj-rev-bwfs-dasmoto#2]
https://github.com/amitkb3/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtNCraft/resources/css/style.css#L6

The background image is not appearing so I think there may be an issue with your path. Revisit this to take a look. I see you are using a similar path in your images on the html page, but since this is in the css file in a different location, you may need to adjust this resource path a bit. The code is correct on how you should paste a background image though, so good work!

**Comment by amitkb3** [comment]
thanks for your feedback.
