### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by Tooconfident** [amitkb3/prj-rev-bwfs-dasmoto#3]
https://github.com/amitkb3/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtNCraft/resources/css/style.css#L12-L31

There is a lot of repetitive code here in the css, so we should look to clean this up. It's good practice to try make your code DRY, if you give your product section and common class and then just give the `<h2>` elements an id you can accomplish this and you CSS can look like so:

https://gist.github.com/Tooconfident/b0b123bbe139f69202b1b9e4e38dd17d

This comes from the html looking like so:

https://gist.github.com/Tooconfident/21095a045d4a3828eb1c860200589917

**Comment by amitkb3** [comment]
thanks for feedback.
