### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tooconfident** [amitkb3/prj-rev-bwfs-dasmoto#4]
Grade: Needs Improvement

Good work! Visually everything looks great and you have a solid understanding of how html relates to CSS so that's good. Going forward I would looks into the important ways of keeping your code DRY (Don't Repeat Yourself), especially in your CSS. You have a lot of styling on multiple html selectors that can be cleaned up by giving those HTML elements the same class and only having to code the style once.

Also don't forget the difference between id's and classes. It is good practice to remember that if you are going to use that selector on more than one element, it is best to make it a class. Id's usually should only show up once in an html file.

**Comment by amitkb3** [comment]
thanks for the feedback.
